### ISSUE TITLE
Example code displays the 2nd page of results

### ISSUE THREAD

**Issue by jnioche** [qwandor/octopower#184]
https://github.com/qwandor/octopower/blob/7a450323896a0184fa68fbb31583a648e2ec96b4/octopower/examples/readings.rs#L61
but the implementation in the library increments the value of the variable
https://github.com/qwandor/octopower/blob/7a450323896a0184fa68fbb31583a648e2ec96b4/octopower/src/lib.rs#L184

Either call the function with 0 as value or remove the increment to display the first page?

**Comment by qwandor** [comment]
Good point, not sure why I did that. Fixed.
