### ISSUE TITLE
Integrate carbonintensity-api to compute carbon emissions

### ISSUE THREAD

**Issue by jnioche** [qwandor/octopower#189]
I have released an initial version of the [carbonintensity-api](https://crates.io/crates/carbonintensity-api), a better version is coming soon.

@qwandor  how do you think it should be done?

First get all the measurements and if the device is an electricity meter, send the measurements to a new function in the carbonintensity api which would

1. retrieve the carbon intensity values for the period
2. compute the emissions
3. return (timestamp, emissions)
?
Alternatively, from your readings.rs, you could retrieve the carbon intensities for the period and compute the emissions yourself.

**Comment by qwandor** [comment]
I'm not sure that it makes sense to integrate that into this library or octo-influx directly. Someone can certainly use both libraries if they want to and do whatever they like to combine the data, or import both into InfluxDB and do calculations in their dashboard.
