### ISSUE TITLE
Which version(s) of influxDB are supported?

### ISSUE THREAD

**Issue by cartwrightian** [qwandor/octopower#47]
Would be great to know which versions of influxDB are supported? From the config that uses database and username/password, instead of bucket and a token, I am guessing older versions? Thanks!

**Comment by cartwrightian** [comment]
Looks like influx_db_client does not support the v2 api

**Comment by qwandor** [comment]
I've been using InfluxDB 1.8.10, which works, I haven't tried v2 yet. There is a comment on https://github.com/alsuren/mijia-homie/issues/182 with a workaround for v2 which I guess should also work for this project, or you're welcome to send a PR to add support. It looks like `influx_db_client` doesn't support the v2 API so you could either send them a PR to add it, or maybe look into https://crates.io/crates/influxdb2. I'd like to retain support for the v1 API though, so it would need to be a config option to switch between them.

**Comment by cartwrightian** [comment]
Many Thanks, I'll try that workaround this weekend and share results here. I'll check out the other fluxdb library in the coming weeks.

**Comment by cartwrightian** [comment]
I got it working using the workaround for creating a v1 account and using those credentials in the config.

influx v1 auth create --org ORG_NAME --username USERNAME --password PASSWORD --write-bucket BUCKET_ID

Also making sure my database name in the config then matched bucket I wanted using the output from 

influx v1 dbrp list

And finally setting the url to 

http://SOMEHOSTNAME:8086/write

These instructions proved useful as well

https://docs.influxdata.com/influxdb/v2.0/tools/grafana/?t=InfluxQL#view-and-create-influxdb-dbrp-mappings
